name: Build and Push Boutique Images to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/ci-ecr.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  SHA_TAG: sha-${{ github.sha }}

permissions:
  id-token: write # required for aws oidc authentication
  contents: read
  security-events: write # trivy uploads

jobs:
  build-push-sign:
    name: Build, Scan, Sign, Push
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        service: [
          "cartservice",
          "currencyservice",
          "paymentservice",
          "shippingservice",
          "emailservice",
          "checkoutservice",
          "recommendationservice",
          "adservice",
          "loadgenerator",
          "frontend",
          "productcatalogservice"
        ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/online-boutique-eks-github-deploy-app-repo
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Artifacts
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE: ${{ matrix.service }}
        run: |
          echo "Building $SERVICE..."
          
          if [ "$SERVICE" == "cartservice" ]; then
            BUILD_DIR="src/$SERVICE/src"
          else
            BUILD_DIR="src/$SERVICE"
          fi
          
          echo "Navigating to $BUILD_DIR..."
          cd $BUILD_DIR

          IMAGE_URI="$ECR_REGISTRY/online-boutique/$SERVICE:${{ env.SHA_TAG }}"

          docker build -t $IMAGE_URI .
          
          docker push $IMAGE_URI

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.36.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          image-ref: '${{ env.ECR_REGISTRY }}/online-boutique/${{ matrix.service }}:${{ env.SHA_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy Scan Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0

      - name: Sign ECR images
        run: |
          IMAGE_URI="$ECR_REGISTRY/online-boutique/${{ matrix.service }}:${{ env.SHA_TAG }}"
          echo "🔏 Signing Image: $IMAGE_URI"
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "$IMAGE_URI"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}


  gitops-handoff:
    name: Commit to Infrastructure Repository
    needs: build-push-sign
    runs-on: ubuntu-24.04
    steps:
      - name: Configure AWS Credentials Via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/online-boutique-eks-github-deploy-app-repo
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR Registry URI
        id: ecr-uri
        run: |
          echo "REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v7
        with:
          repository: susu10-10/online-boutique-eks-pf
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tags for ECR
        run: |
          cd infra/apps/boutique

          REGISTRY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          for SERVICE in \
            frontend adservice cartservice checkoutservice emailservice \
            paymentservice productcatalogservice recommendationservice \
            shippingservice currencyservice loadgenerator
          do
            echo "Updating $SERVICE to $REGISTRY/online-boutique/$SERVICE:$SHA_TAG"
            kustomize edit set image \
            $REGISTRY/online-boutique/$SERVICE=$REGISTRY/online-boutique/$SERVICE:${{ env.SHA_TAG }}
          done


      - name: Commit infra changes
        run: |
          cd infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/boutique/kustomization.yaml
          git commit -m "chore(gitops): update images to ${{ env.SHA_TAG }}" || exit 0
          git push